### ISSUE TITLE
No PDF generation for Part3A and Part5

### ISSUE THREAD

**Issue by zrgt** [admin-shell-io/aas-specs-antora-ui#5]
Currenty when clicking on the PDF icon for Part3A and Part5, the Page Not Found error is displayed. 

The cause of this issue is that the PDF download link is wrongly generated.

- Part3A:
Generated: https://admin-shell-io.github.io/aas-specs-antora/IDTA-01003-a/v3.1/part-3a-data-specification---iec61360.pdf 
Correct: https://admin-shell-io.github.io/aas-specs-antora/IDTA-01003-a/v3.1/part-3a-data-specification-iec61360.pdf
- Part5:
Generated: https://admin-shell-io.github.io/aas-specs-antora/IDTA-01005/v3.1/part-5-package-file-format-(aasx).pdf
Correct: https://admin-shell-io.github.io/aas-specs-antora/IDTA-01005/v3.1/part-5-package-file-format-aasx.pdf

**Comment by zrgt** [comment]
@monsieuremre please fix

**Comment by monsieuremre** [comment]
I've had a look and I have some ideas on why this happens and how to address it. Will create a pull request soon with a suggested solution.

**Comment by zrgt** [comment]
> I've had a look and I have some ideas on why this happens and how to address it. Will create a pull request soon with a suggested solution.

I think you should look for the function in antora which is responsible for generating a name for PDF based on document name and recreate it in the js function

**Comment by monsieuremre** [comment]
Solved, please check the links.

See:

https://github.com/admin-shell-io/aas-specs-antora-ui/commit/9d2978b31dc74a7ee57261a5bef1b50ddb2e1c06

https://github.com/admin-shell-io/aas-specs-antora-ui/commit/e286bfefdee88208300936c6c1b3c50d670f295a
